In [1]:
import pandas
import numpy

In [17]:
def create_final_score(row):
    
    scoreline = str(row['score1']) + str(row['score2'])
    return '-'.join(sorted(scoreline, reverse=True))

def get_favourite(row):
    
    if row['our_score1'] > row['our_score2']:
        favourite = row['team1']
    elif row['our_score1'] < row['our_score2']:
        favourite = row['team2']
    else:
        favourite = 'Draw'
        
    return favourite

def is_correct_score(score1, score2, predicted_score1, predicted_score2):
    
    if score1 == predicted_score1 and score2 == predicted_score2:
        return True
    else:
        return False
    
def is_close_score(score1, score2, predicted_score1, predicted_score2):
    
    actual_score_difference = score2 - score1
    predicted_score_difference = predicted_score2 - predicted_score1
    
    if is_correct_result(score1, score2, predicted_score1, predicted_score2):
        if actual_score_difference == predicted_score_difference:
            if numpy.abs(score1 - predicted_score1) == 1 and numpy.abs(score2 - predicted_score2) == 1:
                return True
            else:
                return False
        elif numpy.abs(actual_score_difference - predicted_score_difference) == 1 and numpy.abs(score2 - predicted_score2) == 1 and score1 == predicted_score1:
            return True
        elif numpy.abs(actual_score_difference - predicted_score_difference) == 1 and numpy.abs(score1 - predicted_score1) == 1 and score2 == predicted_score2:
            return True
        else:
            return False

def is_correct_result(score1, score2, predicted_score1, predicted_score2):
    
    if score1 > score2 and predicted_score1 > predicted_score2:
        return True
    elif score1 < score2 and predicted_score1 < predicted_score2:
        return True
    elif score1 == score2 and predicted_score1 == predicted_score2:
        return True
    else:
        return False

def calculate_points_per_game(row):
    
    favourite = row['favourite']
    
    score1 = row['score1']
    score2 = row['score2']
    
    if row['team1'] == favourite:
        predicted_score1 = 2
        predicted_score2 = 0
    elif row['team2'] == favourite:
        predicted_score1 = 0
        predicted_score2 = 2
    else:
        predicted_score1 = 1
        predicted_score2 = 1
    
    if is_correct_score(score1, score2, predicted_score1, predicted_score2):
        points = 3
    elif is_close_score(score1, score2, predicted_score1, predicted_score2):
        points = 1.5
    elif is_correct_result(score1, score2, predicted_score1, predicted_score2):
        points = 1
    else:
        points = 0
        
    return points

def calculate_our_points_per_game(row):
    
    score1 = row['score1']
    score2 = row['score2']
    
    predicted_score1 = row['our_score1']
    predicted_score2 = row['our_score2']
    
    if is_correct_score(score1, score2, predicted_score1, predicted_score2):
        points = 3
    elif is_close_score(score1, score2, predicted_score1, predicted_score2):
        points = 1.5
    elif is_correct_result(score1, score2, predicted_score1, predicted_score2):
        points = 1
    else:
        points = 0
        
    return points

In [18]:
data = pandas.read_csv('/Users/laurapallett/data/niclas_thomas/world_cup_results/results.csv')
data['final_score'] = data.apply(lambda row: create_final_score(row), axis=1)
data['favourite'] = data.apply(lambda row: get_favourite(row), axis=1)

In [23]:
pandas.DataFrame(data['final_score'].value_counts())

     final_score
2-0           11
1-0           10
2-1           10
0-0            7
1-1            5
3-2            3
3-1            3
4-1            3
3-0            2
4-2            1
7-0            1
6-2            1
3-3            1
6-1            1
2-2            1

In [20]:
data['points'] = data.apply(lambda row: calculate_our_points_per_game(row), axis=1)
data['points'].sum()

59.5

In [21]:
data.head()

,team1,score1,score2,team2,our_score1,our_score2,final_score,favourite,points
0,Qatar,0,2,Ecuador,0,1,2-0,Ecuador,1.5
1,England,6,2,Iran,2,0,6-2,England,1.0
2,Senegal,0,2,Netherlands,0,1,2-0,Netherlands,1.5
3,USA,1,1,Wales,1,1,1-1,Draw,3.0
4,Argentina,1,2,Saudi Arabia,2,0,2-1,Argentina,0.0

In [22]:
data['points'] = data.apply(lambda row: calculate_points_per_game(row), axis=1)
data['points'].sum()

65.0